// Thin C++ shim between the cxx bridge (src/lib.rs) and GTSAM (ADR 0001).
//
// Narrow by design: graph topology and data are owned by the Rust side; this layer only
// translates POD types at the boundary and forwards to GTSAM. Anything GTSAM throws
// crosses the bridge as Result<…> on the Rust side.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <memory>

#include <gtsam/navigation/ImuFactor.h>
#include <gtsam/nonlinear/NonlinearFactorGraph.h>
#include <gtsam/nonlinear/Values.h>

namespace slam_gtsam {

// Shared structs generated by cxx (full definitions in slam-gtsam-sys/src/lib.rs.h).
struct FfiPose;
struct FfiNavState;
struct FfiVec3;
struct FfiOptimizeStats;

class Preintegrator {
 public:
  Preintegrator(double accel_sigma, double gyro_sigma, double integration_sigma,
                double gravity, const std::array<double, 3>& accel_bias,
                const std::array<double, 3>& gyro_bias);

  void integrate(const std::array<double, 3>& accel, const std::array<double, 3>& gyro,
                 double dt);
  void reset();
  double delta_t() const;
  FfiNavState predict(const FfiNavState& state) const;

  const gtsam::PreintegratedImuMeasurements& pim() const { return pim_; }

 private:
  gtsam::PreintegratedImuMeasurements pim_;
};

class GraphBuilder {
 public:
  void insert_pose(std::uint64_t key, const FfiPose& pose);
  void insert_velocity(std::uint64_t key, const std::array<double, 3>& velocity);
  void insert_bias(std::uint64_t key, const std::array<double, 3>& accel_bias,
                   const std::array<double, 3>& gyro_bias);

  void add_prior_pose(std::uint64_t key, const FfiPose& pose,
                      const std::array<double, 6>& sigmas);
  void add_between_pose(std::uint64_t key_from, std::uint64_t key_to,
                        const FfiPose& relative, const std::array<double, 6>& sigmas);
  void add_prior_velocity(std::uint64_t key, const std::array<double, 3>& velocity,
                          const std::array<double, 3>& sigmas);
  void add_prior_bias(std::uint64_t key, const std::array<double, 3>& accel_bias,
                      const std::array<double, 3>& gyro_bias,
                      const std::array<double, 6>& sigmas);
  void add_imu_factor(std::uint64_t pose_i, std::uint64_t velocity_i, std::uint64_t pose_j,
                      std::uint64_t velocity_j, std::uint64_t bias,
                      const Preintegrator& preintegrated);

  FfiOptimizeStats optimize(std::uint32_t max_iterations);

  FfiPose pose_at(std::uint64_t key) const;
  FfiVec3 velocity_at(std::uint64_t key) const;

  std::size_t num_factors() const { return graph_.size(); }
  std::size_t num_values() const { return values_.size(); }

 private:
  gtsam::NonlinearFactorGraph graph_;
  gtsam::Values values_;  // initial estimates; replaced by the optimum after optimize()
};

std::unique_ptr<GraphBuilder> new_graph_builder();
std::unique_ptr<Preintegrator> new_preintegrator(double accel_sigma, double gyro_sigma,
                                                 double integration_sigma, double gravity,
                                                 const std::array<double, 3>& accel_bias,
                                                 const std::array<double, 3>& gyro_bias);

}  // namespace slam_gtsam
